name: Report clang format

# Runs after the Check clang format workflow (check_clang_format.yml) to
# post a helpful comment to the PR if the check failed.
#
# N.B.: Per https://github.community/t/workflow-runs-not-starting-after-previous-workflow-completes/128345/8
# only the version of this workflow on the master (default) branch
# will be run, regardless of what branch is targetted by the PR being
# checked by check_clang_format.yml.
#
# N.B.: Runs with a read-write repo token.  Do not check out the
# submitted branch!
on:
  workflow_run:
    workflows: ["Check clang format"]
    types:
      - completed

jobs:
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
    - uses: actions/github-script@v5
      with:
        script: |
          // Not sure yet how to find out which PR triggered the run, so
          // dump the whole github.event object to try to find useful
          // information.
          console.log('%o', github.event);
